import { NgModule } from '@angular/core';
import 'hammerjs';
import {
  MatButtonModule,
  MatButtonToggleModule,
  MatCardModule,
  MatCheckboxModule,
  MatChipsModule,
  MatDatepickerModule,
  MatDialogModule,
  MatExpansionModule,
  MatIconModule,
  MatInputModule,
  MatListModule,
  MatMenuModule,
  MatNativeDateModule,
  MatPaginatorModule,
  MatProgressBarModule,
  MatProgressSpinnerModule,
  MatSelectModule,
  MatSidenavModule,
  MatSlideToggleModule,
  MatSnackBarModule,
  MatSortModule,
  MatTableModule,
  MatToolbarModule,
  MatTooltipModule,
  MatBadgeModule,
} from '@angular/material';

@NgModule({
  imports: [
    MatSlideToggleModule,
    MatTableModule,
    MatInputModule,    
    MatSidenavModule,
    MatListModule,
    MatIconModule,
    MatToolbarModule,
    MatButtonModule,    
    MatMenuModule,        
    MatExpansionModule,        
    MatCardModule,    
    MatNativeDateModule,
    MatDialogModule,
    MatCheckboxModule,
    MatSortModule,
    MatChipsModule,
    MatTooltipModule,
    MatProgressBarModule,
    MatDatepickerModule,    
    MatProgressSpinnerModule,
    MatSelectModule,
    MatSnackBarModule,
    MatPaginatorModule,
    MatButtonToggleModule,
    MatBadgeModule,
    MatCardModule

  ],
  exports: [
    MatSlideToggleModule,
    MatTableModule,
    MatInputModule,    
    MatSidenavModule,
    MatListModule,
    MatIconModule,
    MatToolbarModule,
    MatButtonModule,    
    MatMenuModule,        
    MatExpansionModule,        
    MatCardModule,    
    MatNativeDateModule,
    MatDialogModule,
    MatCheckboxModule,
    MatSortModule,
    MatChipsModule,
    MatTooltipModule,
    MatProgressBarModule,
    MatDatepickerModule,    
    MatProgressSpinnerModule,
    MatSelectModule,
    MatSnackBarModule,
    MatPaginatorModule,
    MatButtonToggleModule,
    MatBadgeModule,
    MatCardModule
  ]
})
export class MaterialModule { }
